
modLoader="javafml" #mandatory

loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All rights reserved"

[[mods]] #mandatory

modId="mysticaloaktree" #mandatory

version = "${version}"

displayName="Mystical Oak Tree" #mandatory

logoFile="icon.png" #optional

credits="MehVahdJukaar, Plantkillable" #optional

authors="MehVahdJukaar" #optional

itemIcon="mysticaloaktree:label" #catalogue icon
description='''
If you are 25 or older you MUST play this mod!
'''

[[dependencies.mysticaloaktree]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mysticaloaktree]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mysticaloaktree]]

    modId="moonlight"
    mandatory=true
    versionRange="[1.19.2-2.0.35,]"
    ordering="AFTER"
    side="BOTH"
